### ISSUE TITLE
MatomoProvider is not assignable to type 'IntrinsicAttributes & MatomoProviderProps'

### ISSUE THREAD

**Issue by joeriverhavert** [m4tt72/terminal#14]
MatomoProvider (src/pages/_app.tsx) throws an error with the following error code: 
> Type '{ children: Element; value: MatomoTracker; }' is not assignable to type 'IntrinsicAttributes & MatomoProviderProps'.
>   Property 'children' does not exist on type 'IntrinsicAttributes & MatomoProviderProps'.ts(2322)

**Comment by m4tt72** [comment]
I created a PR to fix this issue on their repo, it has been merged but not yet released. As soon as it gets released, I'll update the matomo lib and this issue will be fixed.
