### ISSUE TITLE
Missing ssh version for proper terminal support

### ISSUE THREAD

**Issue by MrMelon54** [m4tt72/terminal#15]

**Comment by m4tt72** [comment]
Could you please provide more info? I'm not sure I get the issue

**Comment by MrMelon54** [comment]
You should have a custom ssh server that outputs a similar interface to access your website directly from a real terminal

**Comment by m4tt72** [comment]
That will defeat the purpose of what I had in mind with this project, but it's brilliant idea

**Comment by MrMelon54** [comment]
fair enough

**Comment by MrMelon54** [comment]
I'm just gonna close this issue as there is no point keeping it open lol
