### ISSUE TITLE
Emacs and vi

### ISSUE THREAD

**Issue by jcubic** [m4tt72/terminal#16]
You can add real emacs and vi. See my [Git Web Terminal](https://git-terminal.js.org/).
Unfortunately, emacs is in the GUI version.

**Comment by m4tt72** [comment]
I'm afraid adding vim support will be way too overkill for a website that looks like it emulates a terminal, I wanted to keep it as simple as possible, and not create an actual terminal on the web. I'm sure there are other projects that already achieved that. 

Feel free to make a PR tho.

If this project becomes a full terminal with a shell, I'm afraid I'll have to abandon it...
