### ISSUE TITLE
SSL Support for docker container

### ISSUE THREAD

**Issue by lsdjunkie** [m4tt72/terminal#33]
Running terminal from a docker container, how would one enable SSL or HTTPS traffic?
The container is exposed on port 80 and I'm attempting to point Cloudflare DNS to a subdomain on my website running this container. Cloudflare is telling me that the "Webserver is down" and I'm getting a 521 error even though the container is online and the website is accessible via IP Address. 

Would it be a node/yarn configuration option? if so where would i change it

**Comment by m4tt72** [comment]
Hello @lsdjunkie,

If you want SSL, you can either run a separate reverse proxy service that will point to your terminal instance's port "3000", like [nginx](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Docker-Nginx-reverse-proxy-setup-example). Or if you already use cloudflare, you can use their [tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/remote/#set-up-a-tunnel-remotely-dashboard-setup).

**Comment by lsdjunkie** [comment]
Resolved with tunnels, Thank you.
