### ISSUE TITLE
linux/arm64/v8 Docker Support

### ISSUE THREAD

**Issue by LubricantJam** [m4tt72/terminal#36]
Hi, i'm trying to run this on a pi, is it possible to have a build that supports this?

**Comment by m4tt72** [comment]
Hello @LubricantJam,

I suggest you checkout [Nest.js documentation](https://nextjs.org/docs/advanced-features/static-html-export) about exporting the project to static HTML. This will allow you to host the project with nginx (or any other server capable of hosting html) in your rpi.

Cheers
